[package]
name = "ultrasonic1209/zappy"
version = "0.1.22"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Highlighter = "boatbomber/highlighter@0.9.0"

[dev-dependencies]
frktest = "itsfrank/frktest@0.0.2"